export type ResearchEntry = {
  id: string;
  name: string;
  classification: string;
  overview: string;
  researchContext: string[];
  mechanism: string;
  limitations: string;
  regulatoryStatus: string;
  references: string[];
  category: 'Reparative' | 'Metabolic' | 'Cosmetic' | 'Cognitive' | 'Other';
};

const CATEGORIES = ['All', 'Reparative', 'Metabolic', 'Cosmetic', 'Cognitive'] as const;
export { CATEGORIES };

const RESEARCH_DATA: ResearchEntry[] = [
  {
    id: 'bpc-157',
    name: 'BPC-157',
    category: 'Reparative',
    classification: 'Synthetic peptide fragment derived from Body Protection Compound (Gastric)',
    overview:
      'BPC-157 is a pentadecapeptide that is a partial sequence of a body protection compound discovered in human gastric juice. It has been extensively studied in preclinical models for its potential role in tissue organization and healing processes.',
    researchContext: [
      'Tendon and ligament fibroblast models (in vitro)',
      'Gastrointestinal mucosal integrity models (animal)',
      'Skeletal muscle repair models (animal)',
      'Angiogenesis pathways (vascular formation models)',
    ],
    mechanism:
      'Preclinical findings suggest this compound may interact with the nitric oxide system and growth factor pathways (specifically VEGFR2) to modulate cellular migration and vessel formation during tissue repair phases.',
    limitations:
      'The majority of available data derives from rodent models. Robust, large-scale human clinical trials regarding safety and efficacy in healthy populations are currently lacking.',
    regulatoryStatus:
      'This compound is not approved by the FDA or EMA for therapeutic use. It is widely classified as a research chemical.',
    references: [
      'Sikiric P, et al. "Brain-gut Axis and Pentadecapeptide BPC 157." Curr Neuropharmacol. 2016.',
      'Gwyer D, et al. "BPC-157 as a Potential Therapeutic Agent for Tendon Healing." J Orthop. 2019.',
    ],
  },
  { id: 'ghk-cu', name: 'GHK-Cu', category: 'Cosmetic', classification: 'Naturally occurring copper-binding tripeptide', overview: 'GHK-Cu is a tripeptide (glycyl-L-histidyl-L-lysine) with a high affinity for copper ions. It is found naturally in human plasma, saliva, and urine, though concentrations decline with age.', researchContext: ['Dermal fibroblast proliferation models', 'Collagen and elastin synthesis pathways (in vitro)', 'Antioxidant enzyme regulation (in vitro)', 'Wound healing models (animal and limited human)'], mechanism: 'Research indicates GHK-Cu may function as a signaling peptide that modulates the expression of genes involving tissue remodeling, antioxidant defense, and anti-inflammatory responses.', limitations: 'While studied in cosmetic formulations, data regarding systemic administration is primarily preclinical. The bioavailability and systemic safety profile are not fully established in large human cohorts.', regulatoryStatus: 'Used as an ingredient in cosmetic products. Not approved as an injectable drug for systemic therapy.', references: ['Pickart L, et al. "GHK Peptide as a Natural Modulator of Multiple Cellular Pathways in Skin Regeneration." Biomed Res Int. 2015.', 'Dou Y, et al. "The potential of GHK-Cu in skin remodeling and anti-aging." J Dermatol Sci. 2018.'] },
  { id: 'tb-500', name: 'Thymosin Beta-4', category: 'Reparative', classification: 'Synthetic analogue of the naturally occurring protein Thymosin Beta-4', overview: 'Thymosin Beta-4 is a major actin-sequestering protein found in almost all human cells. TB-500 is a synthetic fragment or analogue used in research settings to study cytoskeletal structure and cell motility.', researchContext: ['Actin polymerization dynamics (in vitro)', 'Cellular migration and chemotaxis models', 'Cardiac tissue remodeling models (animal)', 'Corneal wound healing models'], mechanism: 'The compound is hypothesized to promote cell migration (chemotaxis) and angiogenesis by regulating actin polymerization, a fundamental process in the formation of the cytoskeleton.', limitations: 'Human clinical data is extremely limited, with some trials halted or inconclusive. Long-term proliferative effects on tissues have not been fully characterized.', regulatoryStatus: 'Not approved for human therapeutic use. Classified as a research substance.', references: ['Goldstein AL, et al. "Thymosin beta4: actin-sequestering protein moonlights to repair injured tissues." Trends Mol Med. 2012.', 'Philp D, et al. "Thymosin beta4 and its degradative peptides: isoform-specific effects in the heart." Curr Pharm Des. 2010.'] },
  { id: 'semaglutide', name: 'Semaglutide', category: 'Metabolic', classification: 'Glucagon-like peptide-1 (GLP-1) receptor agonist', overview: 'Semaglutide is a modified analogue of human GLP-1, a hormone involved in glucose metabolism and appetite regulation. It has been studied extensively for its role in metabolic function.', researchContext: ['Glucose-dependent insulin secretion pathways', 'Gastric emptying rate models', 'Central nervous system appetite regulation', 'Cardiovascular outcome trials'], mechanism: 'It acts by selectively binding to and activating the GLP-1 receptor, which enhances insulin secretion, suppresses glucagon secretion, and delays gastric emptying.', limitations: 'Requires careful titration to manage gastrointestinal tolerability. Long-term effects on thyroid C-cells have been noted in rodent models, though relevance to humans is debated.', regulatoryStatus: 'Approved by FDA and EMA for specific indications (Type 2 Diabetes, Weight Management). Status varies by formulation and jurisdiction.', references: ['Wilding JPH, et al. "Once-Weekly Semaglutide in Adults with Overweight or Obesity." N Engl J Med. 2021.', 'Dhillon S. "Semaglutide: A Review in Type 2 Diabetes." Drugs. 2018.'] },
  { id: 'tirzepatide', name: 'Tirzepatide', category: 'Metabolic', classification: 'Dual GIP/GLP-1 receptor agonist', overview: 'Tirzepatide is a synthetic peptide that acts as a dual agonist for both the glucose-dependent insulinotropic polypeptide (GIP) and glucagon-like peptide-1 (GLP-1) receptors.', researchContext: ['Glycemic control models', 'Lipid metabolism pathways', 'Body weight regulation trials', 'Hepatosteatosis models'], mechanism: 'By activating both GIP and GLP-1 receptors, it synergistically enhances insulin secretion, delays gastric emptying, and modulates appetite signaling in the hypothalamus.', limitations: 'Gastrointestinal side effects are common. Long-term data on specific receptor downregulation is ongoing.', regulatoryStatus: 'Approved by FDA for specific indications (Type 2 Diabetes, Weight Management).', references: ['Jastreboff AM, et al. "Tirzepatide Once Weekly for the Treatment of Obesity." N Engl J Med. 2022.'] },
  { id: 'nad', name: 'NAD+', category: 'Cognitive', classification: 'Coenzyme (Nicotinamide Adenine Dinucleotide)', overview: 'NAD+ is a coenzyme found in all living cells. It is essential for metabolic processes, specifically redox reactions and energy production via the electron transport chain.', researchContext: ['Mitochondrial function assays', 'Sirtuin (SIRT) activation pathways', 'DNA repair mechanisms (PARP activity)', 'Age-related metabolic decline models'], mechanism: 'NAD+ serves as an electron carrier in metabolic reactions and a substrate for enzymes like sirtuins and PARPs, which regulate cellular aging, DNA repair, and circadian rhythm.', limitations: 'Systemic bioavailability via different administration routes is a subject of ongoing debate. Clinical evidence for anti-aging endpoints in humans is preliminary.', regulatoryStatus: 'Available as a supplement component in some jurisdictions; regulatory status of injectable formulations varies significantly.', references: ['Braidy N, et al. "Role of NAD+ and ADP-ribosylation in DNA repair and longevity." Clin Exp Pharmacol Physiol. 2014.', 'Verdin E. "NAD+ in aging, metabolism, and neurodegeneration." Science. 2015.'] },
  { id: 'ipamorelin', name: 'Ipamorelin', category: 'Metabolic', classification: 'Selective Growth Hormone Secretagogue (Pentapeptide)', overview: 'Ipamorelin is a pentapeptide that mimics ghrelin to stimulate the release of growth hormone. It is known for its high selectivity.', researchContext: ['Pulsatile GH secretion models', 'Bone mineral density', 'Gastric motility (post-operative ileus)'], mechanism: 'Binds to the Ghrelin/GHS receptor in the pituitary to stimulate GH release without significantly elevating ACTH (cortisol) or prolactin.', limitations: 'Short half-life requires frequent administration in research protocols. Efficacy depends on pituitary function.', regulatoryStatus: 'Research chemical. Not approved for general therapeutic use.', references: ['Raun K, et al. "Ipamorelin, the first selective growth hormone secretagogue." Eur J Endocrinol. 1998.'] },
  { id: 'melanotan-2', name: 'Melanotan II', category: 'Cosmetic', classification: 'Synthetic Alpha-MSH analogue', overview: 'Melanotan II is a cyclic lactam analogue of alpha-melanocyte-stimulating hormone. It was originally developed to prevent skin cancer by stimulating tanning.', researchContext: ['Melanogenesis (tanning)', 'Erectile dysfunction', 'Libido enhancement', 'Appetite suppression'], mechanism: 'Non-selectively binds to melanocortin receptors (MC1R, MC3R, MC4R, MC5R). MC1R activation stimulates melanin; MC4R affects libido and appetite.', limitations: 'Significant side effects including nausea, flushing, and spontaneous erections. Long-term safety on nevi (moles) is a concern.', regulatoryStatus: 'Research chemical. Not approved for tanning.', references: ['Dorr RT, et al. "Evaluation of melanotan-II, a superpotent cyclic melanotropic peptide in a pilot phase-I clinical study." Life Sci. 1996.'] },
  { id: 'semax', name: 'Semax', category: 'Cognitive', classification: 'Heptapeptide analogue of ACTH (4-10)', overview: 'Semax is a synthetic peptide derived from a fragment of Adrenocorticotropic Hormone (ACTH). It is widely studied in Russia for neurological conditions.', researchContext: ['Ischemic stroke recovery', 'Cognitive enhancement (memory/attention)', 'BDNF expression', 'Optic nerve disease'], mechanism: 'Increases the expression of Brain-Derived Neurotrophic Factor (BDNF) and modulates neurotransmitter levels (dopamine, serotonin).', limitations: 'Most clinical data is published in Russian journals; Western clinical trials are limited.', regulatoryStatus: 'Approved in Russia and Ukraine. Research chemical elsewhere.', references: ['Manchenko DM, et al. "Semax prevents the death of tyrosine hydroxylase-positive neurons in mixed neuroglial cell cultures." Neurosci Lett. 2010.'] },
  { id: 'selank', name: 'Selank', category: 'Cognitive', classification: 'Tuftsin analogue', overview: 'Selank is a synthetic derivative of the human peptide Tuftsin. It is researched for its anxiolytic (anti-anxiety) and nootropic properties.', researchContext: ['Generalized Anxiety Disorder', 'Immune modulation', 'Learning and memory', 'Brain inflammation'], mechanism: 'Modulates GABA receptors and influences enkephalin degradation, producing calming effects without sedation.', limitations: 'Like Semax, primary clinical data is Eastern European. Western regulatory recognition is absent.', regulatoryStatus: 'Approved in Russia. Research chemical elsewhere.', references: ['Ushakova VM, et al. "Selank affects the expression of genes involved in GABAergic neurotransmission." Front Pharmacol. 2017.'] },
  { id: 'glutathione', name: 'Glutathione', category: 'Reparative', classification: 'Tripeptide (Antioxidant)', overview: 'Glutathione is the body\'s "master antioxidant," a tripeptide composed of glutamine, cysteine, and glycine.', researchContext: ['Oxidative stress reduction', 'Liver health', 'Skin brightening', 'Detoxification'], mechanism: 'Neutralizes free radicals and reactive oxygen species. It is crucial for immune function and tissue repair.', limitations: 'Poor oral bioavailability led to interest in injectable or liposomal forms.', regulatoryStatus: 'Approved as a drug in some countries; supplement/compounded in others.', references: ['Pizzorno J. "Glutathione!" Integr Med (Encinitas). 2014.'] },
  { id: 'pt-141', name: 'PT-141 (Bremelanotide)', category: 'Cosmetic', classification: 'Active metabolite of Melanotan II', overview: 'PT-141 is a de-aminated derivative of Melanotan II, isolated for its sexual function properties with less impact on pigmentation.', researchContext: ['Hypoactive Sexual Desire Disorder (HSDD)', 'Erectile dysfunction'], mechanism: 'Acts on melanocortin receptors (MC4R) in the central nervous system to modulate sexual desire and arousal.', limitations: 'Nausea and blood pressure elevation are known side effects.', regulatoryStatus: 'Approved by FDA (Vyleesi) for HSDD in premenopausal women.', references: ['Kingsberg SA, et al. "Bremelanotide for the treatment of hypoactive sexual desire disorder." Expert Opin Pharmacother. 2020.'] },
  { id: 'thymosin-alpha-1', name: 'Thymosin Alpha-1', category: 'Reparative', classification: 'Thymic peptide', overview: 'Thymosin Alpha-1 is a 28-amino acid peptide naturally produced by the thymus gland. It plays a critical role in immune system regulation.', researchContext: ['T-cell maturation', 'Viral infection models (Hepatitis, Influenza)', 'Vaccine adjuvant response', 'Autoimmune modulation'], mechanism: 'Modulates the immune system by enhancing T-cell function and maturation. It helps restore immune balance.', limitations: 'Expensive to synthesize. Short half-life.', regulatoryStatus: 'Approved in some countries (Zadaxin) for Hepatitis and as an adjuvant. Orphan drug status in others.', references: ['King R, et al. "Thymosin alpha 1: a comprehensive review of the literature." Expert Opin Biol Ther. 2003.'] },
  { id: 'epitalon', name: 'Epitalon', category: 'Cognitive', classification: 'Synthetic tetrapeptide (Pineal)', overview: 'Epitalon (Epithalon) is a synthetic peptide based on the natural pineal peptide Epithalamin. It is central to the "Khavinson peptide" bioregulator theory.', researchContext: ['Telomerase activation', 'Circadian rhythm regulation', 'Longevity models', 'Cancer suppression (animal)'], mechanism: 'Stimulates the pineal gland to produce melatonin and is hypothesized to activate telomerase, potentially elongating telomeres.', limitations: 'Human longevity claims are based on limited, older cohorts. Mechanism is not fully mapped in modern Western literature.', regulatoryStatus: 'Research chemical.', references: ['Khavinson VH. "Peptides and Ageing." Neuro Endocrinol Lett. 2002.'] },
];

export const getResearchEntries = (): ResearchEntry[] => {
  return [...RESEARCH_DATA].sort((a, b) => a.name.localeCompare(b.name));
};

export const getResearchEntryById = (id: string): ResearchEntry | undefined => {
  return RESEARCH_DATA.find((e) => e.id === id);
};
